### ISSUE TITLE
[SOLVED] Fatal Error after Cloning Repository

### ISSUE THREAD

**Issue by asyiqinAzham** [ainanabilahh/omcatalog7#1]
1. Make sure to have composer installed in your PC
2. Run cmd and  cd to you project path for example
    `cd xampp/htdocs/omcatalog7/omcatalog`
3. Update/ Install composer on that path
   `composer install`
4. Try run the server after installation finished
    `php artisan serve`
5. An error "Whoops, looks like something went wrong" will appear after opening http://127.0.0.1:8000 
 on your browser
6. In the project file search for `.env.example` file
7. Rename the file from `.env.example` --> `.env.` (IMPORTANT : place . at the end on .env. when 
    renaming because some error will pop up )
8. Go back to cmd (existing one running) `ctrl+c` to end the server then run this code
   `php artisan key:generate` (purpose to generate `APP_KEY` in `.env` that was blank b4 this)
9. Go back to .env file then open it with any text editor
10. Replace the content only from DB_CONNECTION to DB_PASSWORD to this
     `DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=omcatalog3
DB_USERNAME=root
DB_PASSWORD=`
     Make sure to save okayyy
12. Go back to cmd and run back your server `php artisan serve` , open the link  given and your're done

GOOD LUCK!

**Comment by ainanabilahh** [comment]
Really appreciates this <3

**Comment by SabrinaRozi** [comment]
Nice tips!
